import { defineConfig } from "drizzle-kit";
import { sanitizeEnvValue } from "./src/shared/config/env";
import { loadEnvFiles } from "./src/shared/config/load-env-files";

loadEnvFiles();

const databaseUrl = sanitizeEnvValue(process.env.DATABASE_URL);
if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set (drizzle.config.ts)");
}

export default defineConfig({
  dialect: "postgresql",
  schema: [
    "./src/shared/db/schema.ts",
    "./src/features/auth/schema.ts",
    "./src/features/auth/relations.ts",
    "./src/entities/user/schema.ts",
    "./src/entities/user/relations.ts",
    "./src/entities/organization/schema.ts",
    "./src/entities/organization/relations.ts",
    "./src/entities/organization-settings/schema.ts",
    "./src/entities/organization-settings/relations.ts",
    "./src/entities/membership/schema.ts",
    "./src/entities/membership/relations.ts",
    "./src/entities/organization-invite/schema.ts",
    "./src/entities/organization-invite/relations.ts",
    "./src/entities/api-key/schema.ts",
    "./src/entities/api-key/relations.ts",
    "./src/entities/audit/schema.ts",
    "./src/entities/audit/relations.ts",
    "./src/entities/export-job/schema.ts",
    "./src/entities/export-job/relations.ts",
    "./src/entities/integration-connection/schema.ts",
    "./src/entities/integration-connection/relations.ts",
    "./src/entities/digital-employee/schema.ts",
    "./src/entities/digital-employee/relations.ts",
    "./src/entities/knowledge/schema.ts",
    "./src/entities/knowledge/relations.ts",
    "./src/entities/runtime/schema.ts",
    "./src/entities/runtime/relations.ts",
    "./src/entities/session/schema.ts",
    "./src/entities/session/relations.ts",
    "./src/entities/session-message/schema.ts",
    "./src/entities/session-message/relations.ts",
    "./src/entities/task/schema.ts",
    "./src/entities/task/relations.ts",
    "./src/entities/hq-task/schema.ts",
    "./src/entities/hq-task/relations.ts",
    "./src/entities/work-event/schema.ts",
    "./src/entities/work-event/relations.ts",
    "./src/entities/agent-approval/schema.ts",
    "./src/entities/agent-approval/relations.ts",
    "./src/entities/employee-handoff/schema.ts",
    "./src/entities/employee-handoff/relations.ts",
    "./src/entities/employee-lifecycle/schema.ts",
    "./src/entities/employee-lifecycle/relations.ts",
    "./src/entities/provider-config/schema.ts",
    "./src/entities/provider-config/relations.ts",
    "./src/entities/user-consent/schema.ts",
    "./src/entities/user-consent/relations.ts",
    "./src/entities/employee-mission/schema.ts",
    "./src/entities/employee-mission/relations.ts",
    "./src/entities/mission-schedule/schema.ts",
    "./src/entities/mission-schedule/relations.ts",
    "./src/entities/organization-provider-credential/schema.ts",
    "./src/entities/organization-provider-credential/relations.ts",
    "./src/entities/employee-scenario-session/schema.ts",
    "./src/entities/employee-scenario-session/relations.ts",
    "./src/entities/character-preset/schema.ts",
    "./src/entities/character-preset/relations.ts",
    "./src/entities/employee-character/schema.ts",
    "./src/entities/employee-character/relations.ts",
    "./src/entities/skill/schema.ts",
    "./src/entities/skill/relations.ts",
    "./src/entities/employee-skill/schema.ts",
    "./src/entities/employee-skill/relations.ts",
    "./src/entities/tool-definition/schema.ts",
    "./src/entities/tool-definition/relations.ts",
    "./src/entities/employee-tool/schema.ts",
    "./src/entities/employee-tool/relations.ts",
    "./src/entities/platform-employee-catalog/schema.ts",
    "./src/entities/reward/schema.ts",
    "./src/entities/reward/relations.ts",
  ],
  out: "./drizzle",
  dbCredentials: {
    url: databaseUrl,
  },
  strict: true,
});
